repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: '' # Replace with latest version, for example 'v0.1.8'
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
