services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_USER=admin
      - POSTGRES_DB=stock

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_USER=admin
      - POSTGRES_DB=stock

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    networks:
      - app_network
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - APP_ENV=LOCAL
      - APP_VERSION=0.1.0
      - ASGI_LOGGER=uvicorn.asgi
      - DOCS_URL=/docs
      - OPENAPI_URL=/openapi.json
      - REDOC_URL=/redoc
      - SERVER_HOST=localhost
      - SERVER_PORT=8000
      - SERVER_WORKERS=4
      - POLYGON_API_KEY=${POLYGON_API_KEY?Variable not set}
      - POSTGRES_SERVER=db
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_USER=admin
      - POSTGRES_DB=stock
      - POSTGRES_PORT=5432

volumes:
  db-data:

networks:
  app_network:
